copyright:   "2022"
author:      "Heraldoe"
name:        "Halomoan Geraldo"
title:       "OS222: Operating Systems 2022-2"
githublink:  "https://github.com/Heraldoe/os222"
myloglink:   "/TXT/mylog.txt"
